debug:
  board: true
  enable: true
player2:
  limits:
    memory: 70000000
    time: 5000
  exe: pbrain-hikarunogomoku
player1:
  limits:
    time: 5000
    memory: 70000000
  exe: pbrain-hikarunogomoku
general:
  headless: true
