name: Mirror

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-AIA-500-TLS-5-1-gomoku-xavier.mitault.git

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.KEY_SSH }}
